### ISSUE TITLE
Why not publish your book on GitBook?

### ISSUE THREAD

**Issue by StdioA** [geekinglcq/Translation-of-ISLR-Chinese-#1]
Maybe publishing your book on [GitBook](https://www.gitbook.com/) could make it easier to read. :no_mouth:  
If needed, I'd like to help you on the typesetting work.

~~我也不知道为什么我要用英语~~

**Comment by geekinglcq** [comment]
Gitbook address is https://geekinglcq.gitbooks.io/translation-of-islr-chinese-/content/.

**Comment by StdioA** [comment]
Nice~  
Just close the issue.
